# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('domainId', models.CharField(blank=True, max_length=5, null=True)),
                ('project_brief', models.TextField(blank=True, null=True)),
                ('creator_address', models.CharField(blank=True, max_length=100, null=True)),
                ('creator_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
